# Generated by Django 4.0.2 on 2022-02-09 10:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoServerURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updating_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('geoserver_domain', models.URLField(unique=True)),
                ('geoserver_workspace', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'GeoServer URL',
                'verbose_name_plural': 'GeoServer URL',
                'ordering': ['-publishing_date'],
            },
        ),
        migrations.CreateModel(
            name='WMSLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updating_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=70, unique=True)),
                ('slug_post', models.SlugField(max_length=70, unique=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('wms_layer_name', models.CharField(max_length=100, unique=True)),
                ('wms_layer_style', models.CharField(blank=True, max_length=100, null=True)),
                ('set_max_zoom', models.IntegerField(default=28)),
                ('set_min_zoom', models.IntegerField(default=0)),
                ('set_zindex', models.IntegerField(default=1)),
                ('set_opacity', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('wms_bbox', models.CharField(blank=True, max_length=250, null=True)),
                ('wms_centroid', models.CharField(blank=True, max_length=250, null=True)),
                ('wms_layer_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_geoserver_url', to='gismanager.geoserverurl')),
            ],
            options={
                'verbose_name': 'WMS Layer',
                'verbose_name_plural': 'WMS Layers',
                'ordering': ['-publishing_date'],
            },
        ),
    ]
