# Generated by Django 4.0.2 on 2022-02-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gismanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmslayer',
            name='wms_layer_name',
            field=models.CharField(max_length=100),
        ),
    ]
