# Generated by Django 4.0.2 on 2022-02-27 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_sharedtags_description'),
        ('gismanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webgisproject',
            name='tags',
            field=models.ManyToManyField(related_name='related_webgisprojecttag', to='base.SharedTags'),
        ),
        migrations.AddField(
            model_name='wmslayer',
            name='tags',
            field=models.ManyToManyField(related_name='related_wmstag', to='base.SharedTags'),
        ),
        migrations.AlterField(
            model_name='webgisproject',
            name='basemap1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_basemap1', to='gismanager.basemap'),
        ),
    ]
