# Generated by Django 4.0.2 on 2022-02-15 08:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gismanager', '0002_alter_wmslayer_wms_layer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasemapProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updating_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('user', models.CharField(blank=True, max_length=250, null=True)),
                ('token', models.CharField(blank=True, max_length=250, null=True)),
                ('url', models.TextField()),
            ],
            options={
                'verbose_name': 'Basemap',
                'verbose_name_plural': 'Basemap',
                'ordering': ['-publishing_date'],
            },
        ),
        migrations.CreateModel(
            name='Basemap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updating_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=250)),
                ('basemap_code', models.CharField(blank=True, max_length=250, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releted_basemap_provider', to='gismanager.basemapprovider')),
            ],
            options={
                'verbose_name': 'Basemap',
                'verbose_name_plural': 'Basemap',
                'ordering': ['-publishing_date'],
            },
        ),
    ]
