# Generated by Django 4.0.3 on 2022-05-31 08:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gismanager', '0002_alter_geoserverurl_geoserver_domain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geoserverurl',
            options={},
        ),
        migrations.RemoveField(
            model_name='geoserverurl',
            name='geoserver_workspace',
        ),
        migrations.CreateModel(
            name='GeoserverWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updating_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('geoserver_workspace', models.CharField(max_length=100, unique=True)),
                ('geoserver_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_geoserver_domain', to='gismanager.geoserverurl')),
            ],
            options={
                'verbose_name': 'Geoserver workspace',
                'verbose_name_plural': 'Geoserver workspaces',
                'ordering': ['geoserver_workspace'],
            },
        ),
        migrations.AlterField(
            model_name='ogclayer',
            name='ogc_layer_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_geoserver_url', to='gismanager.geoserverworkspace'),
        ),
    ]
