# Generated by Django 4.0.3 on 2022-05-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gismanager', '0003_alter_geoserverurl_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geoserverurl',
            options={'ordering': ['geoserver_domain'], 'verbose_name': 'Geoserver domain', 'verbose_name_plural': 'Geoserver domains'},
        ),
        migrations.AlterField(
            model_name='geoserverworkspace',
            name='geoserver_workspace',
            field=models.CharField(max_length=100),
        ),
    ]
