# Generated by Django 4.0.2 on 2022-02-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gismanager', '0003_basemapprovider_basemap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basemapprovider',
            options={'ordering': ['-publishing_date'], 'verbose_name': 'Basemap Provider', 'verbose_name_plural': 'Basemap Provider'},
        ),
        migrations.RenameField(
            model_name='basemap',
            old_name='basemap_code',
            new_name='tile_code',
        ),
    ]
