# Generated by Django 4.0.2 on 2022-02-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gismanager', '0004_alter_basemapprovider_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basemapprovider',
            old_name='url',
            new_name='raw_url',
        ),
        migrations.AddField(
            model_name='basemap',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
