# Generated by Django 4.0.2 on 2022-02-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gismanager', '0005_rename_url_basemapprovider_raw_url_basemap_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmslayer',
            name='map_attribution',
            field=models.CharField(default='<a href="https://massimilianomoraca.it/" target="_blank">Massimiliano Moraca</a> has created this map using <a href="https://openlayers.org/" target="_blank">OpenLayers</a>', max_length=250),
        ),
        migrations.AddField(
            model_name='wmslayer',
            name='map_center_latitude',
            field=models.DecimalField(decimal_places=5, default=40.842906, max_digits=10),
        ),
        migrations.AddField(
            model_name='wmslayer',
            name='map_center_longitude',
            field=models.DecimalField(decimal_places=5, default=14.239649, max_digits=10),
        ),
        migrations.AddField(
            model_name='wmslayer',
            name='map_scaleline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wmslayer',
            name='set_zoom_level',
            field=models.IntegerField(default=0),
        ),
    ]
