# Generated by Django 4.0.2 on 2022-02-15 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gismanager', '0006_wmslayer_map_attribution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebGISProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updating_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=70, unique=True)),
                ('slug_post', models.SlugField(max_length=70, unique=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('map_scaleline', models.BooleanField(default=True)),
                ('map_attribution', models.CharField(default='<a href="https://massimilianomoraca.it/" target="_blank">Massimiliano Moraca</a> has created this map using <a href="https://openlayers.org/" target="_blank">OpenLayers</a>', max_length=250)),
                ('map_center_longitude', models.DecimalField(decimal_places=5, default=14.239649, max_digits=10)),
                ('map_center_latitude', models.DecimalField(decimal_places=5, default=40.842906, max_digits=10)),
                ('set_max_zoom', models.IntegerField(default=28)),
                ('set_min_zoom', models.IntegerField(default=0)),
                ('set_zoom_level', models.IntegerField(default=0)),
                ('basemap_layers', models.BooleanField(default=False)),
                ('map_layers', models.BooleanField(default=False)),
                ('basemap', models.ManyToManyField(blank=True, related_name='related_basemap', to='gismanager.Basemap')),
                ('layers', models.ManyToManyField(blank=True, related_name='related_wmslayer', to='gismanager.WMSLayer')),
            ],
            options={
                'verbose_name': 'WebGIS',
                'verbose_name_plural': 'WebGIS',
                'ordering': ['-publishing_date'],
            },
        ),
    ]
