# Generated by Django 4.0.2 on 2022-02-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gismanager', '0007_webgisproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='webgisproject',
            name='contents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webgisproject',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webgisproject',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
