# Generated by Django 4.0.2 on 2022-02-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gismanager', '0008_webgisproject_contents_webgisproject_draft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webgisproject',
            name='map_layers',
        ),
    ]
