# Generated by Django 4.0.2 on 2022-02-15 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gismanager', '0010_remove_webgisproject_basemap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webgisproject',
            name='basemap',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='related_basemap', to='gismanager.basemap'),
            preserve_default=False,
        ),
    ]
