# Generated by Django 4.0.2 on 2022-02-16 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gismanager', '0011_webgisproject_basemap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webgisproject',
            name='basemap',
        ),
    ]
