# Generated by Django 4.0.2 on 2022-02-16 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gismanager', '0012_remove_webgisproject_basemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='webgisproject',
            name='basemap1',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='related_basemap1', to='gismanager.basemap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webgisproject',
            name='basemap2',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='related_basemap2', to='gismanager.basemap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webgisproject',
            name='basemap3',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='related_basemap3', to='gismanager.basemap'),
            preserve_default=False,
        ),
    ]
