# Generated by Django 4.0.2 on 2022-02-16 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gismanager', '0014_alter_webgisproject_basemap1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webgisproject',
            name='basemap2',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, related_name='related_basemap2', to='gismanager.basemap'),
        ),
        migrations.AlterField(
            model_name='webgisproject',
            name='basemap3',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, related_name='related_basemap3', to='gismanager.basemap'),
        ),
    ]
