# Generated by Django 4.0.2 on 2022-02-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gismanager', '0019_webgisproject_main_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webgisproject',
            name='layers',
            field=models.ManyToManyField(blank=True, default=None, related_name='related_wmslayer', to='gismanager.WMSLayer'),
        ),
    ]
