# Generated by Django 4.0.2 on 2022-02-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gismanager', '0023_alter_webgisproject_map_center_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmslayer',
            name='wms_legend_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
