# Generated by Django 4.0.2 on 2022-02-22 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gismanager', '0024_wmslayer_wms_legend_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wmslayer',
            name='wms_legend_img',
        ),
    ]
