# Generated by Django 4.0.2 on 2022-02-26 16:09

from django.db import migrations


def create_admin(apps, schema_editor):
    UserProfile = apps.get_model('usermanager', 'UserProfile')
    UserProfile.objects.create_superuser(
        username='admin',
        password='opengeodata',
    )


def create_user(apps, schema_editor):
    UserProfile = apps.get_model('usermanager', 'UserProfile')
    UserProfile.objects.create_user(
        username='user',
        password='opengeodata',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin),
        migrations.RunPython(create_user),
    ]
