# Generated by Django 3.2.6 on 2022-01-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_planning', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SharedTag',
            new_name='SharedTags',
        ),
    ]
