# Generated by Django 4.0.2 on 2022-02-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitecustomization',
            old_name='logo',
            new_name='site_logo',
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='site_description',
            field=models.CharField(blank=True, default='Ufficio Tecnico Comunale e SIT.', max_length=100, null=True),
        ),
    ]
