# Generated by Django 4.0.2 on 2022-02-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesocialurls',
            name='social_icon',
            field=models.CharField(choices=[('Facebook', '<i class="fab fa-facebook-f"></i>'), ('LinkedIn', '<i class="fab fa-linkedin-in"></i>'), ('Instagram', '<i class="fab fa-instagram"></i>'), ('YouYube', '<i class="fab fa-youtube-f"></i>')], default=1, max_length=250),
            preserve_default=False,
        ),
    ]
