# Generated by Django 4.0.2 on 2022-02-26 15:58
from django.db import migrations

from ..utils import social_netoworks, categories


def set_first_url(apps, schema_editor):
    SiteUrls = apps.get_model('base', 'SiteUrls')
    SiteUrls.objects.create(
        name='null island website',
        url='http://www.null-island.null'
    )


def make_social_network_list(apps, schema_editor):
    SiteSocialUrls = apps.get_model('base', 'SiteSocialUrls')
    for social in social_netoworks:
        SiteSocialUrls.objects.create(
            name=social[0],
            url=social[1],
            icon=social[2],
        )


def make_site_description(apps, schema_editor):
    SiteCustomization = apps.get_model('base', 'SiteCustomization')
    SiteCustomization.objects.create(
        name='null island website',
        domain='www.nullisland.null',
        site_title='OpenGeoData',
        site_logo='default/logo.png',
        site_description='Share GeoData to the World!',
        address='Geolocateme Correctly street, 1, Null Island, 9999888',
        contact_phone='+39 0987543',
        contact_email='mail@email.null',
        contact_official_email='pec-mail@email.null',
    )


def make_default_sharedcategory(apps, schema_editor):
    SharedCategories = apps.get_model('base', 'SharedCategories')
    for category in categories:
        SharedCategories.objects.create(
            title=category[0],
            slug=category[1],
            icon=category[2],
            description=category[3]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_first_url),
        migrations.RunPython(make_social_network_list),
        migrations.RunPython(make_site_description),
        migrations.RunPython(make_default_sharedcategory)
    ]
