# Generated by Django 4.0.2 on 2022-02-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_logo_sitecustomization_site_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecustomization',
            name='address',
            field=models.TextField(blank=True, default='Via della Costituzione, 1, - Città dei Sogni, 9999888', null=True),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='contact_email',
            field=models.EmailField(blank=True, default='mail@email.sito', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='contact_official_email',
            field=models.EmailField(blank=True, default='pec-mail@email.sito', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='contact_phone',
            field=models.CharField(blank=True, default='+39 0987543', max_length=250, null=True),
        ),
    ]
