# Generated by Django 4.0.2 on 2022-02-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedtags',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
