# Generated by Django 4.0.2 on 2022-02-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sitesocialurls_social_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesocialurls',
            name='social_icon',
        ),
    ]
