# Generated by Django 4.0.3 on 2022-05-17 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_organogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organogram',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='releted_sitedetails', to='base.sitecustomization'),
        ),
    ]
