# Generated by Django 4.0.2 on 2022-02-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_sitesocialurls_sitecustomization_social_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesocialurls',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
