# Generated by Django 4.0.2 on 2022-02-04 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_sitesocialurls_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesocialurls',
            name='icon',
        ),
        migrations.AlterField(
            model_name='sitesocialurls',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteurls',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
    ]
