version: '3.7'

services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    container_name: dev_db
    #    ports:
#    - 8300:${DB_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data

  website:
    image: maxdragonheart/${PROJECT_NAME}
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      PROJECT_PORT: ${PROJECT_PORT}
      SECRET_KEY: ${SECRET_KEY}
      DB_ENGINE: ${DB_ENGINE}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    container_name: dev_website
    restart: always
#    command: sh -c "poetry run python3 personal_website/manage.py runserver 0.0.0.0:${PROJECT_PORT}"
#    command: sh -c "poetry run python3 personal_website/manage.py migrate --noinput &&
#                    poetry run python3 personal_website/manage.py createsuperuser --noinput &&
#                    poetry run python3 personal_website/manage.py collectstatic --noinput &&
#                    poetry run python3 personal_website/manage.py runserver 0.0.0.0:${PROJECT_PORT}"
    ports:
      - ${PROJECT_PORT}:${PROJECT_PORT}
    volumes:
      #- website-code:/app/web/personal_website
      - website-static-folder:/app/web/static-folder
      - website-media-folder:/app/web/media-folder
      - website-logs:/app/web/logs
    depends_on:
      - db


volumes:
  db-data:
  #website-code:
  website-static-folder:
  website-media-folder:
  website-logs: