# Generated by Django 3.2.6 on 2022-01-29 19:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filebrowser.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityPlanningCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updating_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug_category', models.SlugField(unique=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='CityPlannningPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updating_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=70, unique=True)),
                ('slug_post', models.SlugField(max_length=70, unique=True)),
                ('header_image', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('contents', tinymce.models.HTMLField(blank=True, null=True)),
                ('draft', models.BooleanField(default=False)),
                ('highlighted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_cityplanning_category', to='city_planning.cityplanningcategory')),
                ('cityplanning_sharedtags', models.ManyToManyField(related_name='related_cityplanning_sharedtags', to='base.SharedTag')),
            ],
            options={
                'verbose_name': 'Contenuto',
                'verbose_name_plural': 'Contenuti',
                'ordering': ['-publishing_date'],
            },
        ),
    ]
