[tool.poetry]
name = "website"
version = "0.1.0"
description = ""
authors = ["Massimiliano Moraca"]
license = "Closed"

[tool.poetry.dependencies]
python = "^3.8"
Django = "3.2.11"
design-django-theme = "^1.4.8"
django-cors-headers = "^3.11.0"
django-environ = "^0.8.1"
django-filebrowser = "^4.0.1"
django-grappelli = "^3.0.2"
django-tinymce = "^3.4.0"
beautifulsoup4 = "^4.10.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
