# Generated by Django 3.2.6 on 2021-08-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_protocols', '0001_initial'),
        ('urbanistica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urbanisticacontenuti',
            name='tags',
        ),
        migrations.AddField(
            model_name='urbanisticacontenuti',
            name='urbanistica_sharedtags',
            field=models.ManyToManyField(related_name='related_urbanistica_sharedtag', to='shared_protocols.SharedTag'),
        ),
    ]
